name: NodeJS with Webpack
on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install_dependencies
        run: npm ci
      
      - name: ts-check
        run: npm run ts-check
      
      - name: code-fix
        run: npm run lint:fix
      
      - name: build
        run: npm run build
      
      - name: clean dir html
        if: github.event_name == 'push'
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: rm -rf /var/www/stroymegatrans.ru/html/out
      
      - name: deploy
        if: github.event_name == 'push'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ""
          source: out/
          target: /var/www/stroymegatrans.ru/html